const fs = require("fs");
const path = require("path");

const messagesDir = path.join(__dirname, "../messages");
const locales = ["ar", "en", "fr", "id", "ja"];

const newTranslations = {
  ar: {
    back: "عودة",
    title: "تحميل عمل جديد",
    subtitle: "أكمل النموذج أدناه لتقديم عملك للمراجعة.",
    mainPhoto: "الصورة الرئيسية للعمل",
    photoFormat: "التنسيق: JPG/PNG، الحد الأقصى 2 ميجابايت.",
    mainInfo: "المعلومات الرئيسية",
    workTitle: "عنوان العمل",
    category: "الفئة",
    categoryHint: "يتم ضبط الفئة تلقائياً بناءً على اختيارك الأولي.",
    description: "الوصف المختصر / الملخص",
    selectCategory: "اختر الفئة...",
    techKTI: "المنهجية / أدوات البحث",
    techIoT: "مكونات الأجهزة / البرامج",
    techLainnya: "التطبيقات المستخدمة",
    techDefault: "التقنيات / الأدوات",
    urlKTI: "رابط المجلة / المقالة",
    urlProg: "رابط التطبيق الحي / العرض التوضيحي",
    urlIoT: "رابط الفيديو / المحاكاة",
    urlLainnya: "رابط العمل (يوتيوب / درايف)",
    urlDefault: "رابط العرض التوضيحي / الموقع",
    githubUrl: "مستودع GitHub (اختياري)",
    featKTI: "النتائج الرئيسية للبحث",
    featLainnya: "تفاصيل / مفهوم العمل",
    featIoT: "الميزات الرئيسية للجهاز",
    featDefault: "الميزات الرئيسية للعمل",
    featDescKTI: "اشرح النقاط أو النتائج المهمة من بحثك.",
    featDescLainnya: "اشرح التفاصيل أو العناصر أو المفاهيم المهمة لعملك.",
    featDescIoT: "اشرح وظائف وعمل الجهاز المصنوع.",
    featDescDefault: "اشرح الميزات المهمة في عملك.",
    sectionTechKTI: "المنهجية والمراجع",
    sectionTechIoT: "المكونات والروابط",
    sectionTechLainnya: "الأدوات والروابط",
    sectionTechDefault: "التقنيات والروابط",
    addPoint: "إضافة نقطة",
    addDetail: "إضافة تفاصيل",
    addFeature: "إضافة ميزة",
    point: "نقطة",
    detail: "تفاصيل",
    feature: "ميزة",
    team: "أعضاء الفريق",
    addMember: "إضافة عضو",
    projectLead: "قائد المشروع",
    member: "عضو",
    gallery: "معرض التوثيق",
    addPhoto: "إضافة صورة",
    caption: "وصف الصورة...",
    photo: "صورة",
    sending: "جاري الإرسال...",
    submit: "إرسال تقديم العمل",
    unsavedTitle: "لم يتم حفظ التغييرات",
    unsavedDesc: "هل أنت متأكد أنك تريد المغادرة؟ لن يتم حفظ التغييرات.",
    cancel: "إلغاء",
    leave: "نعم، غادر",
    toastErrorFields: "يرجى إكمال جميع الحقول المحددة باللون الأحمر!",
    toastLogin: "يجب تسجيل الدخول لتحميل العمل.",
    toastSuccess: "تم تقديم العمل بنجاح! يرجى انتظار المراجعة.",
    toastError: "حدث خطأ أثناء تحميل العمل."
  },
  en: {
    back: "Back",
    title: "Upload New Work",
    subtitle: "Complete the form below to submit your work for review by BEM.",
    mainPhoto: "Main Work Photo",
    photoFormat: "Format: JPG/PNG, max 2MB.",
    mainInfo: "Main Information",
    workTitle: "Work Title",
    category: "Category",
    categoryHint: "Category is automatically adjusted based on your initial selection.",
    description: "Short Description / Abstract",
    selectCategory: "Select Category...",
    techKTI: "Research Methods / Tools",
    techIoT: "Hardware / Software Components",
    techLainnya: "Applications Used",
    techDefault: "Tech Stack / Tools",
    urlKTI: "Journal / Paper Link",
    urlProg: "Live Demo / App Link",
    urlIoT: "Video / Simulation Link",
    urlLainnya: "Work Link (YouTube/Drive)",
    urlDefault: "Live Demo / Website URL",
    githubUrl: "GitHub Repository (Optional)",
    featKTI: "Main Research Findings",
    featLainnya: "Work Details / Concept",
    featIoT: "Main Device Features",
    featDefault: "Main Work Features",
    featDescKTI: "Explain the important points or findings from your research.",
    featDescLainnya: "Explain the details, elements, or important concepts of your work.",
    featDescIoT: "Explain the functions and how the device works.",
    featDescDefault: "Explain the important features in your work.",
    sectionTechKTI: "Methodology & References",
    sectionTechIoT: "Components & Links",
    sectionTechLainnya: "Tools & Links",
    sectionTechDefault: "Tech Stack & Links",
    addPoint: "Add Point",
    addDetail: "Add Detail",
    addFeature: "Add Feature",
    point: "Point",
    detail: "Detail",
    feature: "Feature",
    team: "Team Members",
    addMember: "Add Member",
    projectLead: "Project Lead",
    member: "Member",
    gallery: "Documentation Gallery",
    addPhoto: "Add Photo",
    caption: "Caption...",
    photo: "Photo",
    sending: "Sending Data...",
    submit: "Submit Work",
    unsavedTitle: "Unsaved Changes",
    unsavedDesc: "Are you sure you want to leave? Changes will not be saved.",
    cancel: "Cancel",
    leave: "Yes, Leave",
    toastErrorFields: "Please complete all fields marked in red!",
    toastLogin: "You must be logged in to upload work.",
    toastSuccess: "Work submitted successfully! Please wait for review.",
    toastError: "An error occurred while uploading work."
  },
  fr: {
    back: "Retour",
    title: "Télécharger une nouvelle œuvre",
    subtitle: "Remplissez le formulaire ci-dessous pour soumettre votre travail.",
    mainPhoto: "Photo principale",
    photoFormat: "Format : JPG/PNG, max 2 Mo.",
    mainInfo: "Informations principales",
    workTitle: "Titre de l'œuvre",
    category: "Catégorie",
    categoryHint: "La catégorie est ajustée automatiquement.",
    description: "Description courte / Résumé",
    selectCategory: "Sélectionnez une catégorie...",
    techKTI: "Méthodes de recherche",
    techIoT: "Composants matériels / logiciels",
    techLainnya: "Applications utilisées",
    techDefault: "Technologies / Outils",
    urlKTI: "Lien de journal / article",
    urlProg: "Lien de démo",
    urlIoT: "Lien de vidéo",
    urlLainnya: "Lien (YouTube/Drive)",
    urlDefault: "URL du site / démo",
    githubUrl: "Dépôt GitHub (Optionnel)",
    featKTI: "Principales conclusions",
    featLainnya: "Détails / Concept",
    featIoT: "Caractéristiques principales",
    featDefault: "Fonctionnalités principales",
    featDescKTI: "Expliquez les points importants de votre recherche.",
    featDescLainnya: "Expliquez les détails de votre travail.",
    featDescIoT: "Expliquez le fonctionnement de l'appareil.",
    featDescDefault: "Expliquez les fonctionnalités importantes.",
    sectionTechKTI: "Méthodologie et références",
    sectionTechIoT: "Composants et liens",
    sectionTechLainnya: "Outils et liens",
    sectionTechDefault: "Technologies et liens",
    addPoint: "Ajouter un point",
    addDetail: "Ajouter un détail",
    addFeature: "Ajouter une fonctionnalité",
    point: "Point",
    detail: "Détail",
    feature: "Fonctionnalité",
    team: "Membres de l'équipe",
    addMember: "Ajouter un membre",
    projectLead: "Chef de projet",
    member: "Membre",
    gallery: "Galerie de documentation",
    addPhoto: "Ajouter une photo",
    caption: "Légende...",
    photo: "Photo",
    sending: "Envoi en cours...",
    submit: "Soumettre le travail",
    unsavedTitle: "Modifications non enregistrées",
    unsavedDesc: "Êtes-vous sûr de vouloir quitter ?",
    cancel: "Annuler",
    leave: "Oui, Quitter",
    toastErrorFields: "Veuillez remplir tous les champs !",
    toastLogin: "Vous devez être connecté.",
    toastSuccess: "Travail soumis avec succès !",
    toastError: "Une erreur s'est produite."
  },
  id: {
    back: "Kembali",
    title: "Upload Karya Baru",
    subtitle: "Lengkapi formulir di bawah ini untuk mengajukan karyamu agar dapat direview oleh BEM.",
    mainPhoto: "Foto Utama Karya",
    photoFormat: "Format: JPG/PNG, maksimal 2MB.",
    mainInfo: "Informasi Utama",
    workTitle: "Judul Karya",
    category: "Kategori",
    categoryHint: "Kategori otomatis disesuaikan dengan pilihanmu di awal.",
    description: "Deskripsi Singkat / Abstrak",
    selectCategory: "Pilih Kategori...",
    techKTI: "Metode / Tools Penelitian",
    techIoT: "Komponen Hardware / Software",
    techLainnya: "Aplikasi yang Digunakan",
    techDefault: "Tech Stack / Tools",
    urlKTI: "Link Jurnal / Makalah",
    urlProg: "Link Live Demo / App",
    urlIoT: "Link Video / Simulasi",
    urlLainnya: "Link Karya (YouTube/Drive)",
    urlDefault: "Live Demo / Website URL",
    githubUrl: "GitHub Repository (Opsional)",
    featKTI: "Temuan Utama Penelitian",
    featLainnya: "Detail / Konsep Karya",
    featIoT: "Fitur Utama Alat",
    featDefault: "Fitur Utama Karya",
    featDescKTI: "Jelaskan poin-poin penting atau temuan dari hasil penelitianmu.",
    featDescLainnya: "Jelaskan detail, elemen, atau konsep penting dari karyamu.",
    featDescIoT: "Jelaskan fungsi dan cara kerja alat yang dibuat.",
    featDescDefault: "Jelaskan fitur-fitur penting yang ada di dalam karyamu.",
    sectionTechKTI: "Metodologi & Referensi",
    sectionTechIoT: "Komponen & Tautan",
    sectionTechLainnya: "Tools & Tautan",
    sectionTechDefault: "Tech Stack & Tautan",
    addPoint: "Tambah Poin",
    addDetail: "Tambah Detail",
    addFeature: "Tambah Fitur",
    point: "Poin",
    detail: "Detail",
    feature: "Fitur",
    team: "Anggota Tim",
    addMember: "Tambah Anggota",
    projectLead: "Project Lead",
    member: "Anggota",
    gallery: "Galeri Dokumentasi",
    addPhoto: "Tambah Foto",
    caption: "Keterangan...",
    photo: "Foto",
    sending: "Mengirim Data...",
    submit: "Kirim Pengajuan Karya",
    unsavedTitle: "Perubahan Belum Disimpan",
    unsavedDesc: "Apakah kamu yakin ingin keluar? Perubahan tidak akan tersimpan.",
    cancel: "Batal",
    leave: "Ya, Keluar",
    toastErrorFields: "Harap lengkapi semua kolom yang ditandai merah!",
    toastLogin: "Anda harus login untuk upload karya.",
    toastSuccess: "Karya berhasil diajukan! Silakan tunggu review dari BEM.",
    toastError: "Terjadi kesalahan saat upload karya."
  },
  ja: {
    back: "戻る",
    title: "新しい作品をアップロード",
    subtitle: "作品を提出するには、以下のフォームに入力してください。",
    mainPhoto: "メイン写真",
    photoFormat: "形式：JPG/PNG、最大2MB。",
    mainInfo: "主な情報",
    workTitle: "作品タイトル",
    category: "カテゴリ",
    categoryHint: "カテゴリは自動的に調整されます。",
    description: "簡単な説明 / 要約",
    selectCategory: "カテゴリを選択...",
    techKTI: "調査方法 / ツール",
    techIoT: "ハードウェア / ソフトウェア",
    techLainnya: "使用したアプリ",
    techDefault: "技術スタック / ツール",
    urlKTI: "ジャーナル / 論文リンク",
    urlProg: "デモ / アプリリンク",
    urlIoT: "ビデオ / シミュレーションリンク",
    urlLainnya: "作品リンク (YouTube/Drive)",
    urlDefault: "ライブデモ / ウェブサイトURL",
    githubUrl: "GitHubリポジトリ (オプション)",
    featKTI: "主な研究成果",
    featLainnya: "作品の詳細 / コンセプト",
    featIoT: "主なデバイス機能",
    featDefault: "主な作品機能",
    featDescKTI: "研究の重要なポイントを説明してください。",
    featDescLainnya: "作品の詳細やコンセプトを説明してください。",
    featDescIoT: "デバイスの機能と仕組みを説明してください。",
    featDescDefault: "作品の重要な機能を説明してください。",
    sectionTechKTI: "方法論と参考文献",
    sectionTechIoT: "コンポーネントとリンク",
    sectionTechLainnya: "ツールとリンク",
    sectionTechDefault: "技術スタックとリンク",
    addPoint: "ポイントを追加",
    addDetail: "詳細を追加",
    addFeature: "機能を追加",
    point: "ポイント",
    detail: "詳細",
    feature: "機能",
    team: "チームメンバー",
    addMember: "メンバーを追加",
    projectLead: "プロジェクトリーダー",
    member: "メンバー",
    gallery: "ドキュメンテーションギャラリー",
    addPhoto: "写真を追加",
    caption: "キャプション...",
    photo: "写真",
    sending: "送信中...",
    submit: "作品を送信",
    unsavedTitle: "未保存の変更",
    unsavedDesc: "本当に終了しますか？ 変更は保存されません。",
    cancel: "キャンセル",
    leave: "はい、終了します",
    toastErrorFields: "赤でマークされたすべてのフィールドに入力してください！",
    toastLogin: "作品をアップロードするにはログインする必要があります。",
    toastSuccess: "作品が正常に送信されました！",
    toastError: "エラーが発生しました。"
  }
};

for (const locale of locales) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    data.UploadForm = newTranslations[locale];
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${locale}.json`);
  }
}
