const fs = require("fs");
const path = require("path");

const messagesDir = path.join(__dirname, "../messages");
const locales = ["ar", "en", "fr", "id", "ja"];

const newTranslations = {
  ar: {
    title: "لوحة تحكم الأعمال",
    desc: "إدارة ومراقبة حالة أعمالك الابتكارية هنا.",
    uploadNew: "+ تحميل عمل جديد",
    emptyTitle: "لا توجد أعمال حتى الآن",
    emptyDesc: "مساحة العرض الخاصة بك لا تزال فارغة. هيا شارك ابتكاراتك الآن وكن مصدر إلهام!",
    uploadFirst: "قم بتحميل عملك الأول",
    tabAll: "الكل",
    tabPending: "قيد المعالجة",
    tabApproved: "عام",
    tabRejected: "مرفوض",
    catAll: "جميع الفئات",
    catWeb: "تطبيقات الويب والنظام",
    catMobile: "تطبيقات الجوال",
    catResearch: "الأبحاث والمقالات",
    catIoT: "مشاريع إنترنت الأشياء",
    catDesign: "التصميم وغيرها",
    emptyCategory: "لا توجد أعمال في هذه الفئة.",
    uploaded: "تم الرفع:",
    views: "مشاهدات",
    likes: "إعجابات",
    pendingReview: "في انتظار المراجعة",
    approved: "تمت الموافقة (عام)",
    editPending: "تعديل قيد المراجعة",
    editRejected: "تم رفض التعديل",
    deleteRejected: "تم رفض الحذف",
    rejected: "تم رفض التقديم",
    viewNote: "عرض الملاحظة",
    deletePending: "في انتظار الحذف",
    deletedByAdmin: "تم حذفه من قبل الإدارة",
    viewPage: "عرض الصفحة",
    edit: "تعديل",
    close: "إغلاق",
    delete: "حذف"
  },
  en: {
    title: "Work Dashboard",
    desc: "Manage and monitor the status of your innovative works here.",
    uploadNew: "Upload New Work",
    emptyTitle: "No Works Yet",
    emptyDesc: "Your exhibition space is still empty. Share your innovations now and be an inspiration!",
    uploadFirst: "Upload Your First Work",
    tabAll: "All",
    tabPending: "Pending",
    tabApproved: "Public",
    tabRejected: "Rejected",
    catAll: "All Categories",
    catWeb: "Web & System Apps",
    catMobile: "Mobile Apps",
    catResearch: "Research & Journals",
    catIoT: "IoT Projects",
    catDesign: "Design & Others",
    emptyCategory: "No works in this category.",
    uploaded: "Uploaded:",
    views: "Views",
    likes: "Likes",
    pendingReview: "Pending Review",
    approved: "Approved (Public)",
    editPending: "Edit Pending",
    editRejected: "Edit Rejected",
    deleteRejected: "Delete Rejected",
    rejected: "Submission Rejected",
    viewNote: "View Note",
    deletePending: "Deletion Pending",
    deletedByAdmin: "Deleted by Admin",
    viewPage: "View Page",
    edit: "Edit",
    close: "Close",
    delete: "Delete"
  },
  fr: {
    title: "Tableau de Bord des Oeuvres",
    desc: "Gérez et surveillez l'état de vos œuvres innovantes ici.",
    uploadNew: "Télécharger une Nouvelle Œuvre",
    emptyTitle: "Pas Encore d'Œuvres",
    emptyDesc: "Votre espace d'exposition est encore vide. Partagez vos innovations maintenant et soyez une inspiration !",
    uploadFirst: "Téléchargez Votre Première Œuvre",
    tabAll: "Tout",
    tabPending: "En Cours",
    tabApproved: "Public",
    tabRejected: "Rejeté",
    catAll: "Toutes les Catégories",
    catWeb: "App Web & Système",
    catMobile: "App Mobile",
    catResearch: "Recherche & Journaux",
    catIoT: "Projets IoT",
    catDesign: "Design & Autres",
    emptyCategory: "Aucune œuvre dans cette catégorie.",
    uploaded: "Téléchargé :",
    views: "Vues",
    likes: "J'aime",
    pendingReview: "En attente de révision",
    approved: "Approuvé (Public)",
    editPending: "Modification en attente",
    editRejected: "Modification rejetée",
    deleteRejected: "Suppression rejetée",
    rejected: "Soumission rejetée",
    viewNote: "Voir la note",
    deletePending: "Suppression en attente",
    deletedByAdmin: "Supprimé par l'admin",
    viewPage: "Voir la Page",
    edit: "Modifier",
    close: "Fermer",
    delete: "Supprimer"
  },
  id: {
    title: "Dashboard Karya",
    desc: "Kelola dan pantau status karya inovasimu di sini.",
    uploadNew: "Upload Karya Baru",
    emptyTitle: "Belum Ada Karya",
    emptyDesc: "Ruang pameranmu masih kosong nih. Yuk, bagikan inovasimu sekarang dan jadilah inspirasi!",
    uploadFirst: "Upload Karya Pertamamu",
    tabAll: "Semua",
    tabPending: "Proses",
    tabApproved: "Publik",
    tabRejected: "Ditolak",
    catAll: "Semua Kategori",
    catWeb: "Aplikasi Web & Sistem",
    catMobile: "Aplikasi Mobile",
    catResearch: "Karya Tulis & Jurnal",
    catIoT: "Proyek IoT",
    catDesign: "Desain & Lainnya",
    emptyCategory: "Tidak ada karya di kategori ini.",
    uploaded: "Diunggah:",
    views: "Dilihat",
    likes: "Disukai",
    pendingReview: "Menunggu Review",
    approved: "Disetujui (Publik)",
    editPending: "Edit Menunggu Review",
    editRejected: "Edit Ditolak",
    deleteRejected: "Hapus Ditolak",
    rejected: "Pengajuan Ditolak",
    viewNote: "Lihat Catatan",
    deletePending: "Menunggu Hapus",
    deletedByAdmin: "Dihapus Admin",
    viewPage: "Lihat Halaman",
    edit: "Edit",
    close: "Tutup",
    delete: "Hapus"
  },
  ja: {
    title: "作品ダッシュボード",
    desc: "ここであなたの革新的な作品のステータスを管理・監視します。",
    uploadNew: "新しい作品をアップロード",
    emptyTitle: "まだ作品がありません",
    emptyDesc: "あなたの展示スペースはまだ空です。今すぐイノベーションを共有して、インスピレーションになりましょう！",
    uploadFirst: "最初の作品をアップロード",
    tabAll: "すべて",
    tabPending: "処理中",
    tabApproved: "公開",
    tabRejected: "拒否",
    catAll: "すべてのカテゴリー",
    catWeb: "ウェブ＆システムアプリ",
    catMobile: "モバイルアプリ",
    catResearch: "研究＆ジャーナル",
    catIoT: "IoTプロジェクト",
    catDesign: "デザイン＆その他",
    emptyCategory: "このカテゴリーには作品がありません。",
    uploaded: "アップロード日:",
    views: "ビュー",
    likes: "いいね",
    pendingReview: "レビュー待ち",
    approved: "承認済み (公開)",
    editPending: "編集待ち",
    editRejected: "編集が拒否されました",
    deleteRejected: "削除が拒否されました",
    rejected: "提出が拒否されました",
    viewNote: "メモを見る",
    deletePending: "削除待ち",
    deletedByAdmin: "管理者により削除",
    viewPage: "ページを表示",
    edit: "編集",
    close: "閉じる",
    delete: "削除"
  }
};

for (const locale of locales) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    data.DashboardKarya = newTranslations[locale];
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${locale}.json`);
  }
}
