const fs = require("fs");
const path = require("path");

const messagesDir = path.join(__dirname, "../messages");
const locales = ["ar", "en", "fr", "id", "ja"];

const newTranslations = {
  ar: {
    back: "عودة",
    title: "تعديل العمل",
    subtitle: "قم بتحديث بيانات عملك. العمل المعدل سيعود لحالة قيد المراجعة.",
    mainPhoto: "الصورة الرئيسية للعمل",
    photoFormat: "التنسيق: JPG/PNG، الحد الأقصى 2 ميجابايت. سيستخدم كغلاف للعمل.",
    mainInfo: "المعلومات الرئيسية",
    workTitle: "عنوان العمل",
    category: "الفئة",
    description: "الوصف / الملخص",
    techKTI: "الأدوات والمنهجية",
    techIoT: "مكونات الأجهزة والبرامج",
    techLainnya: "التقنيات المستخدمة",
    techDefault: "التقنيات / الأدوات",
    urlKTI: "رابط المجلة / المقالة",
    urlProg: "رابط التطبيق الحي / العرض التوضيحي",
    urlIoT: "رابط الفيديو / المحاكاة",
    urlLainnya: "رابط العمل (يوتيوب / درايف)",
    urlDefault: "رابط العرض التوضيحي / الموقع",
    githubUrl: "مستودع GitHub",
    featKTI: "النتائج الرئيسية",
    featLainnya: "تفاصيل العمل",
    featIoT: "الميزات الرئيسية",
    featDefault: "الميزات الرئيسية",
    sectionTechKTI: "المنهجية والمراجع",
    sectionTechIoT: "المكونات والروابط",
    sectionTechLainnya: "الأدوات والروابط",
    sectionTechDefault: "التقنيات والروابط",
    addPoint: "إضافة نقطة",
    addDetail: "إضافة تفاصيل",
    addFeature: "إضافة ميزة",
    point: "نقطة",
    detail: "تفاصيل",
    feature: "ميزة",
    team: "أعضاء الفريق",
    addMember: "إضافة عضو",
    projectLead: "قائد المشروع",
    member: "عضو",
    gallery: "معرض / عملية الصنع",
    galleryDesc: "قم بتحميل صور إضافية متعلقة بهذا العمل.",
    addPhoto: "إضافة صورة",
    caption: "تعليق الصورة...",
    photo: "صورة",
    emptyGallery: "لا توجد صور في المعرض بعد.",
    saving: "جاري حفظ التغييرات...",
    submit: "حفظ التغييرات وتقديم إعادة مراجعة",
    unsavedTitle: "لم يتم حفظ التغييرات",
    unsavedDesc: "هل أنت متأكد أنك تريد المغادرة؟ سيتم فقدان جميع الإدخالات.",
    cancel: "إلغاء",
    leave: "نعم، غادر",
    toastErrorFields: "يرجى التحقق من الحقول المحددة باللون الأحمر!",
    toastLogin: "يجب تسجيل الدخول لتعديل العمل.",
    toastSuccess: "تم تحديث العمل بنجاح! يرجى انتظار المراجعة.",
    toastError: "حدث خطأ أثناء حفظ العمل.",
    toastNoChanges: "لم يتم إجراء أي تغييرات.",
    toastLoadError: "فشل تحميل بيانات العمل",
    toastDraftLoaded: "تم إعادة تحميل مسودة محفوظة.",
    loading: "جاري تحميل بيانات العمل...",
    namePlaceholder: "الاسم الكامل",
    rolePlaceholder: "الدور"
  },
  en: {
    back: "Back",
    title: "Edit Work",
    subtitle: "Update your work data. Edited work will return to Pending Review status.",
    mainPhoto: "Main Work Photo",
    photoFormat: "Format: JPG/PNG, max 2MB. Used as work cover.",
    mainInfo: "Main Information",
    workTitle: "Work Title",
    category: "Category",
    description: "Description / Abstract",
    techKTI: "Tools & Methodology",
    techIoT: "Hardware & Software Components",
    techLainnya: "Tech Stack",
    techDefault: "Tech Stack / Tools",
    urlKTI: "Journal / Paper Link",
    urlProg: "Live Demo / App Link",
    urlIoT: "Video / Simulation Link",
    urlLainnya: "Work Link (YouTube/Drive)",
    urlDefault: "Live Demo / Website URL",
    githubUrl: "GitHub Repository",
    featKTI: "Main Findings",
    featLainnya: "Work Details",
    featIoT: "Main Features",
    featDefault: "Main Features",
    sectionTechKTI: "Methodology & References",
    sectionTechIoT: "Components & Links",
    sectionTechLainnya: "Tools & Links",
    sectionTechDefault: "Tech Stack & Links",
    addPoint: "Add Point",
    addDetail: "Add Detail",
    addFeature: "Add Feature",
    point: "Point",
    detail: "Detail",
    feature: "Feature",
    team: "Team Members",
    addMember: "Add Member",
    projectLead: "Project Lead",
    member: "Member",
    gallery: "Gallery / Making Process",
    galleryDesc: "Upload additional photos related to this work.",
    addPhoto: "Add Photo",
    caption: "Photo caption...",
    photo: "Photo",
    emptyGallery: "No gallery photos yet.",
    saving: "Saving Changes...",
    submit: "Save Changes & Resubmit for Review",
    unsavedTitle: "Unsaved Changes",
    unsavedDesc: "Are you sure you want to leave? All entries will be lost.",
    cancel: "Cancel",
    leave: "Yes, Leave",
    toastErrorFields: "Please check fields marked in red!",
    toastLogin: "You must be logged in to edit work.",
    toastSuccess: "Work updated successfully! Please wait for review.",
    toastError: "An error occurred while saving work.",
    toastNoChanges: "No changes were made.",
    toastLoadError: "Failed to load work data",
    toastDraftLoaded: "Saved draft reloaded.",
    loading: "Loading work data...",
    namePlaceholder: "Full Name",
    rolePlaceholder: "Role"
  },
  fr: {
    back: "Retour",
    title: "Modifier l'œuvre",
    subtitle: "Mettez à jour les données. L'œuvre modifiée retournera en statut En attente de révision.",
    mainPhoto: "Photo principale",
    photoFormat: "Format : JPG/PNG, max 2 Mo.",
    mainInfo: "Informations principales",
    workTitle: "Titre de l'œuvre",
    category: "Catégorie",
    description: "Description / Résumé",
    techKTI: "Outils & Méthodologie",
    techIoT: "Composants matériels & logiciels",
    techLainnya: "Technologies",
    techDefault: "Technologies / Outils",
    urlKTI: "Lien de journal / article",
    urlProg: "Lien de démo",
    urlIoT: "Lien de vidéo",
    urlLainnya: "Lien (YouTube/Drive)",
    urlDefault: "URL du site / démo",
    githubUrl: "Dépôt GitHub",
    featKTI: "Conclusions",
    featLainnya: "Détails",
    featIoT: "Caractéristiques",
    featDefault: "Fonctionnalités",
    sectionTechKTI: "Méthodologie et références",
    sectionTechIoT: "Composants et liens",
    sectionTechLainnya: "Outils et liens",
    sectionTechDefault: "Technologies et liens",
    addPoint: "Ajouter un point",
    addDetail: "Ajouter un détail",
    addFeature: "Ajouter une fonctionnalité",
    point: "Point",
    detail: "Détail",
    feature: "Fonctionnalité",
    team: "Membres de l'équipe",
    addMember: "Ajouter un membre",
    projectLead: "Chef de projet",
    member: "Membre",
    gallery: "Galerie / Processus",
    galleryDesc: "Téléchargez des photos supplémentaires.",
    addPhoto: "Ajouter une photo",
    caption: "Légende...",
    photo: "Photo",
    emptyGallery: "Aucune photo.",
    saving: "Sauvegarde en cours...",
    submit: "Enregistrer et soumettre",
    unsavedTitle: "Modifications non enregistrées",
    unsavedDesc: "Êtes-vous sûr de vouloir quitter ?",
    cancel: "Annuler",
    leave: "Oui, Quitter",
    toastErrorFields: "Veuillez vérifier les champs en rouge !",
    toastLogin: "Vous devez être connecté.",
    toastSuccess: "Travail mis à jour avec succès !",
    toastError: "Erreur lors de la sauvegarde.",
    toastNoChanges: "Aucune modification apportée.",
    toastLoadError: "Échec du chargement.",
    toastDraftLoaded: "Brouillon rechargé.",
    loading: "Chargement...",
    namePlaceholder: "Nom complet",
    rolePlaceholder: "Rôle"
  },
  id: {
    back: "Kembali",
    title: "Edit Karya",
    subtitle: "Perbarui data karyamu. Karya yang diedit akan kembali berstatus Menunggu Review.",
    mainPhoto: "Foto Utama Karya",
    photoFormat: "Format: JPG/PNG, maksimal 2MB. Akan digunakan sebagai cover karya.",
    mainInfo: "Informasi Utama",
    workTitle: "Judul Karya",
    category: "Kategori",
    description: "Deskripsi / Abstrak",
    techKTI: "Tools & Metodologi",
    techIoT: "Komponen Hardware & Software",
    techLainnya: "Tech Stack",
    techDefault: "Tech Stack",
    urlKTI: "Link Jurnal / Makalah",
    urlProg: "Link Live Demo / App",
    urlIoT: "Link Video / Simulasi",
    urlLainnya: "Link Karya (YouTube/Drive)",
    urlDefault: "Live Demo / Link Karya",
    githubUrl: "GitHub Repository",
    featKTI: "Temuan Utama",
    featLainnya: "Detail Karya",
    featIoT: "Fitur Utama",
    featDefault: "Fitur Utama",
    sectionTechKTI: "Tools & Metodologi",
    sectionTechIoT: "Komponen Hardware & Software",
    sectionTechLainnya: "Tech Stack",
    sectionTechDefault: "Tech Stack & Tautan",
    addPoint: "Tambah Poin",
    addDetail: "Tambah Detail",
    addFeature: "Tambah Fitur",
    point: "Poin",
    detail: "Detail",
    feature: "Fitur",
    team: "Anggota Tim",
    addMember: "Tambah Anggota",
    projectLead: "Project Lead",
    member: "Anggota",
    gallery: "Galeri / Proses Pembuatan",
    galleryDesc: "Unggah foto-foto tambahan terkait karya ini.",
    addPhoto: "Tambah Foto",
    caption: "Keterangan foto...",
    photo: "Foto",
    emptyGallery: "Belum ada foto galeri.",
    saving: "Menyimpan Perubahan...",
    submit: "Simpan Perubahan & Ajukan Review Ulang",
    unsavedTitle: "Perubahan Belum Disimpan",
    unsavedDesc: "Apakah kamu yakin ingin keluar? Semua isian pada form ini akan hilang jika belum disimpan.",
    cancel: "Batal",
    leave: "Ya, Keluar",
    toastErrorFields: "Periksa kembali input yang salah!",
    toastLogin: "Anda harus login untuk mengedit karya.",
    toastSuccess: "Karya berhasil diperbarui! Silakan tunggu review ulang dari BEM.",
    toastError: "Terjadi kesalahan saat menyimpan karya.",
    toastNoChanges: "Tidak ada perubahan yang dilakukan.",
    toastLoadError: "Gagal memuat data karya",
    toastDraftLoaded: "Draft tersimpan dimuat ulang.",
    loading: "Memuat data karya...",
    namePlaceholder: "Nama Lengkap",
    rolePlaceholder: "Peran"
  },
  ja: {
    back: "戻る",
    title: "作品を編集",
    subtitle: "作品データを更新します。編集した作品はレビュー待ち状態に戻ります。",
    mainPhoto: "メイン写真",
    photoFormat: "形式：JPG/PNG、最大2MB。",
    mainInfo: "主な情報",
    workTitle: "作品タイトル",
    category: "カテゴリ",
    description: "説明 / 要約",
    techKTI: "ツールと方法論",
    techIoT: "ハードウェアとソフトウェア",
    techLainnya: "技術スタック",
    techDefault: "技術スタック / ツール",
    urlKTI: "ジャーナル / 論文リンク",
    urlProg: "デモ / アプリリンク",
    urlIoT: "ビデオ / シミュレーションリンク",
    urlLainnya: "作品リンク (YouTube/Drive)",
    urlDefault: "ライブデモ / ウェブサイトURL",
    githubUrl: "GitHubリポジトリ",
    featKTI: "主な調査結果",
    featLainnya: "作品の詳細",
    featIoT: "主な機能",
    featDefault: "主な機能",
    sectionTechKTI: "方法論と参考文献",
    sectionTechIoT: "コンポーネントとリンク",
    sectionTechLainnya: "ツールとリンク",
    sectionTechDefault: "技術スタックとリンク",
    addPoint: "ポイントを追加",
    addDetail: "詳細を追加",
    addFeature: "機能を追加",
    point: "ポイント",
    detail: "詳細",
    feature: "機能",
    team: "チームメンバー",
    addMember: "メンバーを追加",
    projectLead: "プロジェクトリーダー",
    member: "メンバー",
    gallery: "ギャラリー / 制作過程",
    galleryDesc: "関連する追加の写真をアップロードします。",
    addPhoto: "写真を追加",
    caption: "キャプション...",
    photo: "写真",
    emptyGallery: "ギャラリー写真はありません。",
    saving: "保存中...",
    submit: "変更を保存して再提出",
    unsavedTitle: "未保存の変更",
    unsavedDesc: "本当に終了しますか？",
    cancel: "キャンセル",
    leave: "はい、終了します",
    toastErrorFields: "赤でマークされたフィールドを確認してください！",
    toastLogin: "ログインする必要があります。",
    toastSuccess: "作品が正常に更新されました！",
    toastError: "エラーが発生しました。",
    toastNoChanges: "変更は行われませんでした。",
    toastLoadError: "データの読み込みに失敗しました",
    toastDraftLoaded: "下書きが再読み込みされました。",
    loading: "データを読み込み中...",
    namePlaceholder: "フルネーム",
    rolePlaceholder: "役割"
  }
};

for (const locale of locales) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    data.EditForm = newTranslations[locale];
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${locale}.json`);
  }
}
